import React from 'react';

export const metadata = {
  title: 'IDB Mail Assistant',
  description: 'Generated by IDB Inc.',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className="bg-slate-50">{children}</body>
    </html>
  );
}
